### ISSUE TITLE
trust-store port to wayland

### ISSUE THREAD

**Issue by mariogrip** [ubports/trust-store#7]
Currently trust store uses the mirclient trust api to draw on top of windows.

**Comment by dobey** [comment]
Making this work correctly will require `xdg-foreign` protocol support in Mir.

**Comment by z3ntu** [comment]
mirclient APIs have been dropped with Mir 2.0.0

**Comment by peat-psuwit** [comment]
Migrated to GitLab.

https://gitlab.com/ubports/core/trust-store/-/issues/2
